sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake

env:
  - TERM=dumb
  
matrix:
    include:
    - os: linux
      language: java
      jdk:  openjdk11
      install: true
    - os: linux
      language: java
      jdk:  openjdk12
      install: true
    - os: osx
      language: java
      jdk:  openjdk11
      install: true
    - os: osx
      language: java
      jdk:  openjdk12
      install: true

#cache:
#  ccache: true
#  directories:
#   - /Users/travis/build/miho/

before_script:
    - sh ./gradlew clean assemble --no-daemon
script:
    - export CWD=$(pwd)
    - sh ./gradlew test --no-daemon