# Get Azure Pipelines free plan
# Visit https://azure.microsoft.com/en-us/services/devops/pipelines/

trigger:
  - master

jobs:  

  # Linux job
  
  - template: ./build-job-unix.yml
    parameters:
      name: Linux_JDK_11
      platform: linux
      jdkVersion: 1.11
      pool:
        vmImage: 'ubuntu-16.04'
    
  # Mac OS job
        
  - template: ./build-job-unix.yml
    parameters:
      name: MacOS_JDK_11
      platform: mac
      jdkVersion: 1.11
      pool:
        vmImage: 'macOS-10.13'    
       

  # Windows job
  
  - template: build-job-windows.yml
    parameters:
      name: Windows_JDK_11
      platform: win
      jdkVersion: 1.11
      pool:
        vmImage: 'windows-2019'
        