parameters:
  name: ''
  pool: ''
  platform: ''
  jdkVersion: '1.11'
  gradleWrapperFile: 'gradlew.bat'
  workingDirectory: ''
  tasks: 'clean assemble test'

jobs:
- job: '__${{ parameters.name }}__'
  pool: ${{ parameters.pool }}
  steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: './gradlew'
        workingDirectory: './'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        jdkArchitectureOption: 'x64'
        #publishJUnitResults: true
        #testResultsFiles: '**/TEST-*.xml'
        tasks: 'clean assemble'
    - task: Gradle@2
      inputs:
        gradleWrapperFile: './gradlew'
        workingDirectory: './'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: ${{ parameters.jdkVersion }}
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'test'
