parameters:
  name: ''
  pool: ''
  platform: ''
  jdkVersion: '1.11'
  gradleWrapperFile: 'gradlew.bat'
  workingDirectory: ''
  tasks: 'clean build'

jobs:
- job: '__${{ parameters.name }}__'
  pool: ${{ parameters.pool }}
  steps:

    - bash: ./gradlew clean assemble test